import NavigationMenu from '@/components/NavigationMenu'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='fixed top-4 left-4'>
          <NavigationMenu />
        </div>
        {children}

      </body>
    </html>
  )
}
